num1 = int(input("First Number : "))
num2 = int(input("Second Number : "))
print(num1,"+",num2,"=",num1 + num2)
print(num1,"-",num2,"=",num1 - num2)
print(num1,"x",num2,"=",num1 * num2)
print(num1,"÷",num2,"=",int(num1 / num2))